# Generated by Django 5.0.7 on 2024-07-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_book_title_book_name_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
